INSERT INTO albums (id, title, artist, img, category) VALUES 
('Perfect', 'Perfect', 'Ed Sheeran', 'https://justvibestorage.blob.core.windows.net/albumimages/Perfect.jpg', 'Romantic'),
('GunturKaaram', 'Guntur Kaaram', 'Thaman S', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg', 'Action'),
('ArjunReddy', 'Arjun Reddy', 'Radhan & Harshvardhan Rameshwar', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg', 'Romantic'),
('Devara', 'Devara', 'Anirudh Ravichander', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg', 'Action'),
('GameChanger', 'Game Changer', 'Thaman S', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg', 'Action'),
('Pushpa2', 'Pushpa 2', 'Devi Sri Prasad', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg', 'Action'),
('OG', 'OG', 'Thaman S', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg', 'Action'),
('KGF2', 'KGF 2', 'Ravi Basrur', 'https://justvibestorage.blob.core.windows.net/albumimages/KGF2.jpg', 'Action'),
('LoveYourVoice', 'Love Your Voice', 'JONY', 'https://justvibestorage.blob.core.windows.net/albumimages/LoveYourVoice.jpg', 'Romantic'),
('ShapeOfYou', 'Shape Of You', 'Ed Sheeran', 'https://justvibestorage.blob.core.windows.net/albumimages/ShapeOfYou.jpg', 'Happy'),
('Die With A Smile', 'Die With A Smile', 'Lady Gaga and Bruno Mars', 'https://justvibestorage.blob.core.windows.net/albumimages/Die With A Smile.jpg', 'Romantic');

INSERT INTO songs (album_id, title, src, img) VALUES
('Perfect', 'Perfect', 'https://justvibestorage.blob.core.windows.net/music/Perfect/Perfect.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Perfect.jpg'),
('GunturKaaram', 'Guntur Kaaram', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Guntur Kaaram.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('GunturKaaram', 'Kurchi Madathapetti', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Kurchi Madathapetti.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('GunturKaaram', 'Dum Masala', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Dum Masala.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('GunturKaaram', 'Oh My Baby', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Oh My Baby.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('GunturKaaram', 'Mawaa Enthaina', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Mawaa Enthaina.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('GunturKaaram', 'Ramana Aei', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Ramana Aei.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('GunturKaaram', 'Amma', 'https://justvibestorage.blob.core.windows.net/music/Guntur Kaaram/Amma.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GunturKaaram.jpg'),
('ArjunReddy', 'Dhooram', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Dhooram.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('ArjunReddy', 'Emitemitemo', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Emitemitemo.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('ArjunReddy', 'Gundelonaa', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Gundelonaa.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('ArjunReddy', 'Madhurame', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Madhurame.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('ArjunReddy', 'Mari Mari', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Mari Mari.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('ArjunReddy', 'Oopiri Aaguthunnadey', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Oopiri Aaguthunnadey.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('ArjunReddy', 'Telisiney Na Nuvvey', 'https://justvibestorage.blob.core.windows.net/music/Arjun Reddy/Telisiney Na Nuvvey.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ArjunReddy.jpg'),
('Devara', 'Fear', 'https://justvibestorage.blob.core.windows.net/music/Devara/Fear.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg'),
('Devara', 'Chuttamalle', 'https://justvibestorage.blob.core.windows.net/music/Devara/Chuttamalle.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg'),
('Devara', 'Daavudi', 'https://justvibestorage.blob.core.windows.net/music/Devara/Daavudi.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg'),
('Devara', 'Ayudha Pooja', 'https://justvibestorage.blob.core.windows.net/music/Devara/Ayudha Pooja.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg'),
('Devara', 'Red Sea', 'https://justvibestorage.blob.core.windows.net/music/Devara/Red Sea.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg'),
('Devara', 'All Hail The Tiger', 'https://justvibestorage.blob.core.windows.net/music/Devara/All Hail The Tiger.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Devara1.jpg'),
('GameChanger', 'Jaragandi', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Jaragandi.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Raa Macha Macha', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Raa Macha Macha.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Naanaa Hyraanaa', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Naanaa Hyraanaa.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Dhop', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Dhop.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Arugu Meedha', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Arugu Meedha.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Konda Devara', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Konda Devara.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Koparap', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Koparap.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('GameChanger', 'Unpredictable', 'https://justvibestorage.blob.core.windows.net/music/Game Changer/Unpredictable.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/GameChanger1.jpg'),
('Pushpa2', 'Pushpa Pushpa', 'https://justvibestorage.blob.core.windows.net/music/Pushpa 2/Pushpa Pushpa.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg'),
('Pushpa2', 'Sooseki', 'https://justvibestorage.blob.core.windows.net/music/Pushpa 2/Sooseki.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg'),
('Pushpa2', 'Kissik', 'https://justvibestorage.blob.core.windows.net/music/Pushpa 2/Kissik.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg'),
('Pushpa2', 'Peelings', 'https://justvibestorage.blob.core.windows.net/music/Pushpa 2/Peelings.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg'),
('Pushpa2', 'Gango Renuka Thalli', 'https://justvibestorage.blob.core.windows.net/music/Pushpa 2/Gango Renuka Thalli.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg'),
('Pushpa2', 'Dammunte Pattukora', 'https://justvibestorage.blob.core.windows.net/music/Pushpa 2/Dammunte Pattukora.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Pushpa2.jpg'),
('OG', 'Hungry Cheetah', 'https://justvibestorage.blob.core.windows.net/music/OG/Hungry Cheetah.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg'),
('OG', 'Fire Storm', 'https://justvibestorage.blob.core.windows.net/music/OG/Fire Storm.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg'),
('OG', 'Suvvi Suvvi', 'https://justvibestorage.blob.core.windows.net/music/OG/Suvvi Suvvi.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg'),
('OG', 'Guns And Roses', 'https://justvibestorage.blob.core.windows.net/music/OG/Guns And Roses.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg'),
('OG', 'Washi O Washi', 'https://justvibestorage.blob.core.windows.net/music/OG/Washi O Washi.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg'),
('OG', 'Trance of OMI', 'https://justvibestorage.blob.core.windows.net/music/OG/Trance of OMI.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/OG.jpg'),
('KGF2', 'Toofan', 'https://justvibestorage.blob.core.windows.net/music/KGF 2/Toofan.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/KGF2.jpg'),
('KGF2', 'Yadagara Yadagara', 'https://justvibestorage.blob.core.windows.net/music/KGF 2/Yadagara Yadagara.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/KGF2.jpg'),
('KGF2', 'Sultan', 'https://justvibestorage.blob.core.windows.net/music/KGF 2/Sulthana.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/KGF2.jpg'),
('KGF2', 'Mehabooba', 'https://justvibestorage.blob.core.windows.net/music/KGF 2/Mehabooba.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/KGF2.jpg'),
('KGF2', 'The Monster', 'https://justvibestorage.blob.core.windows.net/music/KGF 2/The Monster.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/KGF2.jpg'),
('LoveYourVoice', 'JONY - Love your voice', 'https://justvibestorage.blob.core.windows.net/music/Love Your Voice/JONY - Love your voice.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/LoveYourVoice.jpg'),
('ShapeOfYou', 'Ed Sheeran - Shape of You', 'https://justvibestorage.blob.core.windows.net/music/Shape Of You/Ed Sheeran - Shape of You.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/ShapeOfYou.jpg'),
('Die With A Smile', 'Die With A Smile', 'https://justvibestorage.blob.core.windows.net/music/Die With A Smile/Die With A Smile.mp3', 'https://justvibestorage.blob.core.windows.net/albumimages/Die With A Smile.jpg');
